apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
        - name: traffic-generator
          image: {{ .Values.image.trafficGenerator }}
          ports:
            - containerPort: 8081
