apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-stats
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traffic-stats
  template:
    metadata:
      labels:
        app: traffic-stats
    spec:
      containers:
        - name: traffic-stats
          image: {{ .Values.image.trafficStats }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "traffic_db"
