apiVersion: v1
kind: Service
metadata:
  name: traffic-stats
spec:
  type: {{ .Values.service.trafficStats.type }}
  ports:
    - port: {{ .Values.service.trafficStats.port }}
      targetPort: 8080
  selector:
    app: traffic-stats
