apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: {{ .Values.service.postgres.type }}
  ports:
    - port: {{ .Values.service.postgres.port }}
      targetPort: 5432
  selector:
    app: postgres
