version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: traffic_data_20_mar
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  traffic-stats-col:
    build: ./traffic-stats-col
    container_name: traffic-stats-col
    restart: always
    depends_on:
      postgres-db:
        condition: service_healthy
    environment:
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: traffic_data_20_mar
    ports:
      - "8080:8080"
    networks:
      - app_network

  traffic-generator:
    build: ./traffic-generator
    container_name: traffic-generator
    restart: "no"
    depends_on:
      - traffic-stats-col
    environment:
      API_URL: "http://traffic-stats-col:8080/collect"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
