replicaCount: 1

image:
  trafficGenerator: "jathins/traffic-generator:latest"
  trafficStats: "jathins/traffic-stats-col:latest"
  postgres: "postgres:latest"

service:
  trafficGenerator:
    type: ClusterIP
    port: 8081
  trafficStats:
    type: ClusterIP
    port: 8080
  postgres:
    type: ClusterIP
    port: 5432

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false   # Set to true if you want autoscaling
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
